artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://drive.google.com/file/d/1IsBKeRAXGJ-Y6Bxo8RA2_BPqSzwvU3L7/view?usp=sharing
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion